apply plugin: 'com.android.application'

android {
    namespace "com.droid.videoRecorder"
    compileSdk 36

    defaultConfig {
        applicationId "com.droid.videoRecorder"
        minSdk 24
        targetSdk 36
        versionCode 32
        versionName "11.0"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.google.mediapipe:tasks-vision:0.10.35'
    implementation 'androidx.media3:media3-transformer:1.10.1'
    implementation 'androidx.media3:media3-effect:1.10.1'
    implementation 'androidx.media3:media3-common:1.10.1'
    testImplementation 'junit:junit:4.13.2'
}
